### PR TITLE
Added controlled usage

### PR DESCRIPTION
**Pull request by adrienthiery**
Make the component controllable by passing a new Index property (Issue #5) 

Was implemented by PR #8 a while ago but never been merged.

### CODE REVIEW

**Comment by Darkbladecr** [comment]
Any chance this can be merged? @esauter5

**Comment by esauter5** [comment]
Works for me 👍

**Comment by esauter5** [comment]
Will update the docs later unless @adrienthiery is able to and then I'll push to npm

**Comment by esauter5** [comment]
Merged. Better late than never I guess 🤷🏻‍♂️

**Comment by adrienthiery** [comment]
🙌

**Pull request merged**
